# Generated by Django 5.2.16 on 2026-09-03 18:39

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'owner'), ('ADMIN', 'admin'), ('MEMBER', 'member'), ('VIEWER', 'viewer')], default='VIEWER', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['OWNER', 'ADMIN', 'MEMBER', 'VIEWER'])), name='role_checker'), models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TODO', 'to do'), ('DONE', 'done'), ('IN_PROGRESS', 'in_progress')], default='TODO', max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['due_date'], name='projects_ta_due_dat_4757e0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', django.db.models.functions.datetime.TruncDate('created_at')), _connector='OR'), name='date_checker'), models.CheckConstraint(condition=models.Q(('status__in', ['TODO', 'DONE', 'IN_PROGRESS'])), name='status_checker')],
            },
        ),
    ]
