# Generated by Django 5.2.16 on 2026-08-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
    ]
