# Generated by Django 5.2.16 on 2026-07-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_status_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'to do'), ('DONE', 'done'), ('IN_PROGRESS', 'in_progress')], default='TODO', max_length=20),
        ),
    ]
