# Generated by Django 5.2.16 on 2026-08-26 14:33

import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_task_date_checker_alter_project_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='date_checker',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='projects_ta_due_dat_4757e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', django.db.models.functions.datetime.TruncDate('created_at')), _connector='OR'), name='date_checker'),
        ),
    ]
